-- AlterTable
ALTER TABLE "User" ADD COLUMN "profileImageUrl" TEXT,
ADD COLUMN "ratingBuyer" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "ratingSeller" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "darkMode" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "Auction" ADD COLUMN "tags" TEXT[] DEFAULT ARRAY[]::TEXT[];
